### ISSUE TITLE
Can't archive all subreddits

### ISSUE THREAD

**Issue by SN4T14** [SN4T14/RedArc.js#4]
if one of the subreddits in subreddits.txt is /r/all, RedArc.js should archive everything.

**Comment by ohhdemgirls** [comment]
Or treat r/all as a single sub? Keeping other listed subs separate instead of just archiving everything and ignoring the other subs in `subreddits.txt` Hmm ..

I'm not dead, just taking some time.

**Comment by SN4T14** [comment]
I'm not sure I understand what you mean? RedArc.js shouldn't remove subreddits or users from their text files or anything, it should just check if /r/all is listed in `subreddits.txt`, and if it is, archive all posts on all subreddits.

Also, glad to hear you're alive, we've all been worried sick about you! :)

**Comment by ohhdemgirls** [comment]
Ahh, sorry I'm with you carry on :p

**Comment by SN4T14** [comment]
Fixed with 2 lines of code in 496e46a.
